export const activities = [
  {
      id: 1,
      title: "Hiking in the Mountains",
      category: "Outdoor",
      moodLevel: "Adventurous",
      description: "Explore scenic trails in the mountains near you.",
  },
  {
      id: 2,
      title: "Yoga and Meditation",
      category: "Wellness",
      moodLevel: "Relaxed",
      description: "Join a local yoga class or practice meditation.",
  },
  {
      id: 3,
      title: "Painting Workshop",
      category: "Indoor",
      moodLevel: "Creative",
      description: "Express your creativity through painting.",
  },
  {
      id: 4,
      title: "Reading Fiction Books",
      category: "Educational",
      moodLevel: "Intellectual",
      description: "Dive into the world of fiction with a good book.",
  },
  {
      id: 5,
      title: "Cooking Class",
      category: "Indoor",
      moodLevel: "Curious",
      description: "Learn new culinary skills in a fun cooking class.",
  },
  {
      id: 6,
      title: "Stargazing Night",
      category: "Outdoor",
      moodLevel: "Calm",
      description: "Observe the beauty of the night sky and stargaze.",
  },
  {
      id: 7,
      title: "Visiting an Art Gallery",
      category: "Educational",
      moodLevel: "Emotional",
      description: "Explore art and experience different emotions.",
  },
  {
      id: 8,
      title: "Listening to Classical Music",
      category: "Wellness",
      moodLevel: "Sad",
      description: "Listen to soothing classical music to relax and reflect.",
  },
  {
      id: 9,
      title: "Solving Puzzles",
      category: "Indoor",
      moodLevel: "Intellectual",
      description: "Challenge your mind with puzzles and brain teasers.",
  },
  {
      id: 10,
      title: "Gardening",
      category: "Outdoor",
      moodLevel: "Relaxed",
      description: "Spend time nurturing plants and gardening.",
  },
  {
      id: 11,
      title: "Visit to a Historical Site",
      category: "Educational",
      moodLevel: "Intellectual",
      description: "Explore history and learn about ancient civilizations.",
  },
  {
      id: 12,
      title: "Movie Marathon",
      category: "Indoor",
      moodLevel: "Relaxed",
      description: "Enjoy back-to-back movies with friends or family.",
  },
  {
      id: 13,
      title: "Writing Poetry",
      category: "Creative",
      moodLevel: "Emotional",
      description: "Express emotions through poetic verses.",
  },
  {
      id: 14,
      title: "Birdwatching",
      category: "Outdoor",
      moodLevel: "Curious",
      description: "Observe and identify birds in their natural habitat.",
  },
  {
      id: 15,
      title: "Museum Exploration",
      category: "Educational",
      moodLevel: "Intellectual",
      description: "Discover artifacts and exhibitions in a local museum.",
  },
  {
      id: 16,
      title: "Listening to Podcasts",
      category: "Wellness",
      moodLevel: "Relaxed",
      description: "Listen to informative or entertaining podcasts.",
  },
  {
      id: 17,
      title: "Volunteering at a Shelter",
      category: "Outdoor",
      moodLevel: "Emotional",
      description: "Make a difference by volunteering at a local shelter.",
  },
  {
      id: 18,
      title: "DIY Craft Workshop",
      category: "Indoor",
      moodLevel: "Creative",
      description: "Create handmade crafts in a DIY workshop.",
  },
  {
      id: 19,
      title: "Outdoor Photography",
      category: "Outdoor",
      moodLevel: "Creative",
      description: "Capture nature's beauty through photography.",
  },
  {
      id: 20,
      title: "Attending a Science Lecture",
      category: "Educational",
      moodLevel: "Intellectual",
      description: "Expand knowledge with a lecture on scientific topics.",
  },
  {
      id: 21,
      title: "Exploring a Botanical Garden",
      category: "Outdoor",
      moodLevel: "Calm",
      description: "Enjoy the serenity and beauty of a botanical garden.",
  },
  {
      id: 22,
      title: "Listening to Live Jazz Music",
      category: "Wellness",
      moodLevel: "Relaxed",
      description: "Experience the soothing sounds of live jazz music.",
  },
  {
      id: 23,
      title: "Learning a New Language",
      category: "Educational",
      moodLevel: "Intellectual",
      description: "Embark on a journey to learn a new language.",
  },
  {
      id: 24,
      title: "Attending a Comedy Show",
      category: "Wellness",
      moodLevel: "Happy",
      description: "Laugh and unwind at a comedy show with friends.",
  },
  {
      id: 25,
      title: "Exploring a New City",
      category: "Outdoor",
      moodLevel: "Adventurous",
      description: "Discover the sights and sounds of a new city.",
  },
  {
      id: 26,
      title: "Pottery Making Workshop",
      category: "Indoor",
      moodLevel: "Creative",
      description: "Create pottery and learn the art of ceramics.",
  },
  {
      id: 27,
      title: "Nature Walk",
      category: "Outdoor",
      moodLevel: "Relaxed",
      description: "Take a peaceful walk in nature and enjoy the surroundings.",
  },
  {
      id: 28,
      title: "Attending a Theater Play",
      category: "Wellness",
      moodLevel: "Emotional",
      description: "Experience the drama and emotions of live theater.",
  },
  {
      id: 29,
      title: "Virtual Reality Gaming",
      category: "Indoor",
      moodLevel: "Adventurous",
      description: "Immerse yourself in virtual worlds and exciting adventures.",
  },
  {
      id: 30,
      title: "Ice Skating",
      category: "Outdoor",
      moodLevel: "Fun",
      description: "Enjoy gliding on ice and skating with friends or family.",
  },
  {
      id: 31,
      title: "Writing Short Stories",
      category: "Creative",
      moodLevel: "Imaginative",
      description: "Create captivating short stories with imaginative plots.",
  },
  {
      id: 32,
      title: "Fishing Trip",
      category: "Outdoor",
      moodLevel: "Relaxed",
      description: "Spend a peaceful day fishing by the lake or river.",
  },
  {
      id: 33,
      title: "Exploring Local Markets",
      category: "Outdoor",
      moodLevel: "Curious",
      description: "Discover unique treasures and local flavors at markets.",
  },
  {
      id: 34,
      title: "Attending a Music Concert",
      category: "Wellness",
      moodLevel: "Energetic",
      description: "Experience the excitement and energy of a live music concert.",
  },
  {
      id: 35,
      title: "Rock Climbing",
      category: "Outdoor",
      moodLevel: "Adventurous",
      description: "Challenge yourself with rock climbing adventures.",
  },
  {
      id: 36,
      title: "Cooking Challenge with Friends",
      category: "Indoor",
      moodLevel: "Competitive",
      description: "Participate in a cooking challenge and showcase culinary skills.",
  },
  {
      id: 37,
      title: "Photography Exhibition",
      category: "Educational",
      moodLevel: "Appreciative",
      description: "Attend a photography exhibition and admire stunning visuals.",
  },
  {
      id: 38,
      title: "Attending a Dance Workshop",
      category: "Wellness",
      moodLevel: "Energetic",
      description: "Learn new dance moves and express yourself through dance.",
  },
  {
      id: 39,
      title: "Beach Day",
      category: "Outdoor",
      moodLevel: "Relaxed",
      description: "Relax on the beach, swim in the ocean, and soak up the sun.",
  },
  {
      id: 40,
      title: "Visit to an Aquarium",
      category: "Educational",
      moodLevel: "Curious",
      description: "Explore marine life and learn about underwater ecosystems.",
  },
  {
      id: 41,
      title: "Baking Desserts",
      category: "Indoor",
      moodLevel: "Sweet",
      description: "Bake delicious desserts and enjoy the sweet treats.",
  },
  {
      id: 42,
      title: "Art and Craft Fair",
      category: "Outdoor",
      moodLevel: "Creative",
      description: "Browse unique artworks and handmade crafts at a local fair.",
  },
  {
      id: 43,
      title: "Astrology Workshop",
      category: "Educational",
      moodLevel: "Curious",
      description: "Learn about astrology and explore cosmic connections.",
  },
  {
      id: 44,
      title: "Forest Bathing",
      category: "Outdoor",
      moodLevel: "Calm",
      description: "Immerse yourself in nature and practice mindfulness in the forest.",
  },
  {
      id: 45,
      title: "Attending a Poetry Slam",
      category: "Wellness",
      moodLevel: "Emotional",
      description: "Experience spoken word poetry and connect through emotional expression.",
  },
  {
      id: 46,
      title: "Botanical Illustration Class",
      category: "Educational",
      moodLevel: "Creative",
      description: "Learn botanical illustration techniques and create beautiful artworks.",
  },
  {
      id: 47,
      title: "Bird Photography",
      category: "Outdoor",
      moodLevel: "Patient",
      description: "Capture stunning images of birds in their natural habitats.",
  },
  {
      id: 48,
      title: "Visiting a Science Museum",
      category: "Educational",
      moodLevel: "Intellectual",
      description: "Explore interactive exhibits and scientific wonders at a science museum.",
  },
  {
      id: 49,
      title: "Tai Chi in the Park",
      category: "Wellness",
      moodLevel: "Relaxed",
      description: "Practice Tai Chi for relaxation and harmony in a serene park setting.",
  },
  {
      id: 50,
      title: "Attending a Film Festival",
      category: "Educational",
      moodLevel: "Cinematic",
      description: "Enjoy a variety of films and engage in cinematic experiences.",
  },
  {
      id: 51,
      title: "Star Wars Marathon",
      category: "Indoor",
      moodLevel: "Nostalgic",
      description: "Watch all the Star Wars movies in chronological order.",
  },
  {
      id: 52,
      title: "Bicycle Tour",
      category: "Outdoor",
      moodLevel: "Adventurous",
      description: "Explore scenic routes and discover new places on a bicycle tour.",
  },
  {
      id: 53,
      title: "Writing a Journal",
      category: "Wellness",
      moodLevel: "Reflective",
      description: "Record thoughts, experiences, and reflections in a personal journal.",
  },
  {
      id: 54,
      title: "Chess Tournament",
      category: "Indoor",
      moodLevel: "Strategic",
      description: "Compete in a chess tournament and showcase strategic thinking.",
  },
  {
      id: 55,
      title: "Sailing Adventure",
      category: "Outdoor",
      moodLevel: "Thrilling",
      description: "Embark on a sailing adventure and feel the thrill of the open waters.",
  },
  {
      id: 56,
      title: "Calligraphy Workshop",
      category: "Indoor",
      moodLevel: "Artistic",
      description: "Learn the art of calligraphy and create beautiful lettering.",
  },
  {
      id: 57,
      title: "Night Photography",
      category: "Outdoor",
      moodLevel: "Mystical",
      description: "Capture the magic of night scenes with photography.",
  },
  {
      id: 58,
      title: "Mindfulness Retreat",
      category: "Wellness",
      moodLevel: "Peaceful",
      description: "Attend a mindfulness retreat to cultivate inner peace and relaxation.",
  },
  {
      id: 59,
      title: "Scuba Diving",
      category: "Outdoor",
      moodLevel: "Exhilarating",
      description: "Explore the underwater world and experience scuba diving adventures.",
  },
  {
      id: 60,
      title: "Exploring Street Art",
      category: "Outdoor",
      moodLevel: "Urban",
      description: "Discover vibrant street art and murals in the city.",
  },
  {
      id: 61,
      title: "Attending a Fashion Show",
      category: "Wellness",
      moodLevel: "Stylish",
      description: "Experience the glamour and creativity of a fashion show.",
  },
  {
      id: 62,
      title: "Potluck Dinner with Friends",
      category: "Indoor",
      moodLevel: "Social",
      description: "Share delicious food and good times with friends at a potluck dinner.",
  },
  {
      id: 63,
      title: "Fossil Hunting",
      category: "Outdoor",
      moodLevel: "Discovery",
      description: "Search for fossils and uncover ancient treasures.",
  },
  {
      id: 64,
      title: "Joining a Book Club",
      category: "Educational",
      moodLevel: "Community",
      description: "Discuss books and connect with fellow book enthusiasts in a book club.",
  },
  {
      id: 65,
      title: "Building a DIY Project",
      category: "Indoor",
      moodLevel: "Innovative",
      description: "Create something unique and useful through a DIY project.",
  },
  {
      id: 66,
      title: "Picnic in the Park",
      category: "Outdoor",
      moodLevel: "Relaxed",
      description: "Enjoy a picnic outdoors with delicious food and nature's beauty.",
  },
  {
      id: 67,
      title: "Virtual Museum Tour",
      category: "Educational",
      moodLevel: "Virtual",
      description: "Explore museums and exhibitions virtually from the comfort of home.",
  },
  {
      id: 68,
      title: "Attending a Wine Tasting",
      category: "Wellness",
      moodLevel: "Sophisticated",
      description: "Sample and appreciate different wines at a wine tasting event.",
  },
  {
      id: 69,
      title: "Whale Watching",
      category: "Outdoor",
      moodLevel: "Exciting",
      description: "Observe majestic whales in their natural habitat on a whale watching tour.",
  },
  {
      id: 70,
      title: "Learning Origami",
      category: "Indoor",
      moodLevel: "Artistic",
      description: "Master the art of origami and create intricate paper designs.",
  },
  {
      id: 71,
      title: "Visit to a Botanical Arboretum",
      category: "Outdoor",
      moodLevel: "Botanical",
      description: "Explore diverse plant collections and scenic landscapes at an arboretum.",
  },
  {
      id: 72,
      title: "Attending a Technology Expo",
      category: "Educational",
      moodLevel: "Futuristic",
      description: "Discover cutting-edge technology and innovations at a tech expo.",
  },
  {
      id: 73,
      title: "Ice Cream Tasting",
      category: "Wellness",
      moodLevel: "Sweet",
      description: "Indulge in a variety of delicious ice cream flavors and treats.",
  },
  {
      id: 74,
      title: "Joining a Community Garden",
      category: "Outdoor",
      moodLevel: "Community",
      description: "Participate in gardening activities and connect with the community.",
  },
  {
      id: 75,
      title: "Attending a Comedy Improv Show",
      category: "Wellness",
      moodLevel: "Hilarious",
      description: "Laugh out loud at a comedy improv show filled with spontaneous humor.",
  },
  {
      id: 76,
      title: "Exploring Caves",
      category: "Outdoor",
      moodLevel: "Adventure",
      description: "Embark on an underground adventure to explore fascinating caves.",
  },
  {
      id: 77,
      title: "Board Game Night with Friends",
      category: "Indoor",
      moodLevel: "Competitive",
      description: "Enjoy friendly competition and fun board games with friends.",
  },
  {
      id: 78,
      title: "Attending a Food Festival",
      category: "Wellness",
      moodLevel: "Gourmet",
      description: "Savor culinary delights and gourmet dishes at a food festival.",
  },
  {
      id: 79,
      title: "Collecting Seashells",
      category: "Outdoor",
      moodLevel: "Relaxing",
      description: "Stroll along the beach and collect beautiful seashells.",
  },
  {
      id: 80,
      title: "Film Making Workshop",
      category: "Educational",
      moodLevel: "Creative",
      description: "Learn film making techniques and create short films.",
  },
  {
      id: 81,
      title: "Horseback Riding",
      category: "Outdoor",
      moodLevel: "Exhilarating",
      description: "Ride horses and explore scenic trails on horseback.",
  },
  {
      id: 82,
      title: "Astrophotography",
      category: "Outdoor",
      moodLevel: "Astronomical",
      description: "Capture stunning images of celestial objects and the night sky.",
  },
  {
      id: 83,
      title: "Visit to a Historical Castle",
      category: "Educational",
      moodLevel: "Historic",
      description: "Explore the rich history and architecture of a medieval castle.",
  },
  {
      id: 84,
      title: "Attending a Stand-Up Comedy Show",
      category: "Wellness",
      moodLevel: "Entertained",
      description: "Enjoy a night of laughter and humor at a stand-up comedy show.",
  },
  {
      id: 85,
      title: "Kayaking Adventure",
      category: "Outdoor",
      moodLevel: "Exciting",
      description: "Paddle through rivers, lakes, or seas on an exhilarating kayaking adventure.",
  },
  {
      id: 86,
      title: "Learning Pottery Wheel Techniques",
      category: "Indoor",
      moodLevel: "Artistic",
      description: "Master pottery wheel techniques and create pottery masterpieces.",
  },
  {
      id: 87,
      title: "Local Farm Visit",
      category: "Outdoor",
      moodLevel: "Educational",
      description: "Learn about sustainable farming practices and enjoy farm activities.",
  },
  {
      id: 88,
      title: "Attending a Dance Performance",
      category: "Wellness",
      moodLevel: "Elegant",
      description: "Watch a mesmerizing dance performance showcasing grace and skill.",
  },
  {
      id: 89,
      title: "Metal Detecting",
      category: "Outdoor",
      moodLevel: "Treasure Hunt",
      description: "Search for hidden treasures with a metal detector in outdoor locations.",
  },
  {
      id: 90,
      title: "Learning Origami",
      category: "Indoor",
      moodLevel: "Artistic",
      description: "Master the art of origami and create intricate paper designs.",
  },
  {
      id: 91,
      title: "Visit to a Botanical Arboretum",
      category: "Outdoor",
      moodLevel: "Botanical",
      description: "Explore diverse plant collections and scenic landscapes at an arboretum.",
  },
  {
      id: 92,
      title: "Attending a Technology Expo",
      category: "Educational",
      moodLevel: "Futuristic",
      description: "Discover cutting-edge technology and innovations at a tech expo.",
  },
  {
      id: 93,
      title: "Ice Cream Tasting",
      category: "Wellness",
      moodLevel: "Sweet",
      description: "Indulge in a variety of delicious ice cream flavors and treats.",
  },
  {
      id: 94,
      title: "Joining a Community Garden",
      category: "Outdoor",
      moodLevel: "Community",
      description: "Participate in gardening activities and connect with the community.",
  },
  {
      id: 95,
      title: "Attending a Comedy Improv Show",
      category: "Wellness",
      moodLevel: "Hilarious",
      description: "Laugh out loud at a comedy improv show filled with spontaneous humor.",
  },
  {
      id: 96,
      title: "Exploring Caves",
      category: "Outdoor",
      moodLevel: "Adventure",
      description: "Embark on an underground adventure to explore fascinating caves.",
  },
  {
      id: 97,
      title: "Board Game Night with Friends",
      category: "Indoor",
      moodLevel: "Competitive",
      description: "Enjoy friendly competition and fun board games with friends.",
  },
  {
      id: 98,
      title: "Attending a Food Festival",
      category: "Wellness",
      moodLevel: "Gourmet",
      description: "Savor culinary delights and gourmet dishes at a food festival.",
  },
  {
      id: 99,
      title: "Collecting Seashells",
      category: "Outdoor",
      moodLevel: "Relaxing",
      description: "Stroll along the beach and collect beautiful seashells.",
  },
  {
      id: 100,
      title: "Film Making Workshop",
      category: "Educational",
      moodLevel: "Creative",
      description: "Learn film making techniques and create short films.",
  },
  // Add more activities as needed
];
